name: griot_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # state management
  flutter_bloc: ^8.0.1

  # Value equality
  equatable: ^2.0.5

  # Function programming thingies  
  dartz: ^0.10.1

  # Remote API
  http: ^0.13.3

  # local storage
  shared_preferences: ^2.0.8

  # check connectivity
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.1
  injectable_generator: ^1.4.1
  build_runner: ^2.1.7

  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
