name: griot_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # state management
  flutter_bloc: ^8.0.1

  # Value equality
  equatable: ^2.0.5

  # Function programming thingies  
  dartz: ^0.10.1

  # Remote API
  http: ^1.0.0
  http_parser: ^4.0.0

  # local storage
  shared_preferences: ^2.0.8
  image_picker: ^0.8.9

  # check connectivity
  internet_connection_checker: ^1.0.0+1

  # video dependencies
  video_compress: ^3.1.0
  chewie: ^1.5.0

  # Dependency Injection
  get_it: ^7.6.0

  # Fonts
  google_fonts: ^5.0.0
  intl: ^0.18.1

  # Notifications
  flash: ^3.0.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.1
  injectable_generator: ^1.4.1
  build_runner: ^2.1.7

  flutter_lints: ^2.0.0
  bloc_test: ^9.1.3

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/logo3x.png
    - assets/vertical@3x - F3F3F3 - White Smoke.png
    
  fonts:
  - family: Poppins
    fonts:
      - asset: fonts/Poppins/Poppins-Black.ttf
      - asset: fonts/Poppins/Poppins-BlackItalic.ttf
        style: italic     
      - asset: fonts/Poppins/Poppins-Bold.ttf
      - asset: fonts/Poppins/Poppins-BoldItalic.ttf
        style: italic     
      - asset: fonts/Poppins/Poppins-ExtraBold.ttf
      - asset: fonts/Poppins/Poppins-ExtraBoldItalic.ttf
        style: italic     
      - asset: fonts/Poppins/Poppins-ExtraLight.ttf
      - asset: fonts/Poppins/Poppins-ExtraLightItalic.ttf
        style: italic     
      - asset: fonts/Poppins/Poppins-Italic.ttf
        style: italic     
      - asset: fonts/Poppins/Poppins-Light.ttf
      - asset: fonts/Poppins/Poppins-LightItalic.ttf
        style: italic     
      - asset: fonts/Poppins/Poppins-Medium.ttf
      - asset: fonts/Poppins/Poppins-MediumItalic.ttf
        style: italic     
      - asset: fonts/Poppins/Poppins-Regular.ttf
      - asset: fonts/Poppins/Poppins-SemiBold.ttf
      - asset: fonts/Poppins/Poppins-SemiBoldItalic.ttf
        style: italic     
      - asset: fonts/Poppins/Poppins-Thin.ttf
      - asset: fonts/Poppins/Poppins-ThinItalic.ttf
        style: italic
  uses-material-design: true
