// Mocks generated by Mockito 5.4.1 from annotations
// in griot_app/test/features/profiles/presentation/bloc/profile_bloc_bloc_test.dart.
// Do not manually edit this file.

// @dart=2.19

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:griot_app/core/error/failures.dart' as _i6;
import 'package:griot_app/profile/domain/entities/profile.dart' as _i7;
import 'package:griot_app/profile/domain/repositories/profile_respository.dart'
    as _i2;
import 'package:griot_app/profile/domain/use_cases/perform_get_profile_details.dart'
    as _i4;
import 'package:griot_app/profile/domain/use_cases/perform_update_profile_dateils.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProfilesRepository_0 extends _i1.SmartFake
    implements _i2.ProfilesRepository {
  _FakeProfilesRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PerformGetProfileDetails].
///
/// See the documentation for Mockito's code generation for more information.
class MockPerformGetProfileDetails extends _i1.Mock
    implements _i4.PerformGetProfileDetails {
  MockPerformGetProfileDetails() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProfilesRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeProfilesRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ProfilesRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Profile>> call(_i4.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.Profile>>.value(
            _FakeEither_1<_i6.Failure, _i7.Profile>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.Profile>>);
}

/// A class which mocks [PerformUpdateProfileDetails].
///
/// See the documentation for Mockito's code generation for more information.
class MockPerformUpdateProfileDetails extends _i1.Mock
    implements _i8.PerformUpdateProfileDetails {
  MockPerformUpdateProfileDetails() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProfilesRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeProfilesRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ProfilesRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Profile>> call(_i8.Params? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.Profile>>.value(
            _FakeEither_1<_i6.Failure, _i7.Profile>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.Profile>>);
}
