// Mocks generated by Mockito 5.4.1 from annotations
// in griot_app/test/features/user/data/repository_impl/user_repository_impl_test.dart.
// Do not manually edit this file.

// @dart=2.19

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:griot_app/accounts/domain/entities/account.dart' as _i4;
import 'package:griot_app/core/error/exceptions.dart' as _i6;
import 'package:griot_app/core/network/network_info.dart' as _i5;
import 'package:griot_app/user/data/data_sources/users_remote_data_source.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [UsersRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUsersRemoteDataSource extends _i1.Mock
    implements _i2.UsersRemoteDataSource {
  MockUsersRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Account>> getBelovedAccountsListFromAPI() =>
      (super.noSuchMethod(
        Invocation.method(
          #getBelovedAccountsListFromAPI,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Account>>.value(<_i4.Account>[]),
      ) as _i3.Future<List<_i4.Account>>);
  @override
  _i3.Future<List<_i4.Account>> getOwnedAccountsListFromAPI() =>
      (super.noSuchMethod(
        Invocation.method(
          #getOwnedAccountsListFromAPI,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Account>>.value(<_i4.Account>[]),
      ) as _i3.Future<List<_i4.Account>>);
  @override
  _i3.Future<void> storeMainAccountId({required int? mainAccountId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeMainAccountId,
          [],
          {#mainAccountId: mainAccountId},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i5.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}

/// A class which mocks [ServerException].
///
/// See the documentation for Mockito's code generation for more information.
class MockServerException extends _i1.Mock implements _i6.ServerException {
  MockServerException() {
    _i1.throwOnMissingStub(this);
  }
}
