// Mocks generated by Mockito 5.4.2 from annotations
// in griot_app/test/features/user/domain/use_cases/get_user_owned_accounts_list_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:griot_app/accounts/domain/entities/account.dart' as _i6;
import 'package:griot_app/core/error/failures.dart' as _i5;
import 'package:griot_app/user/domain/repository/users_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UsersRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUsersRepository extends _i1.Mock implements _i3.UsersRepository {
  MockUsersRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Account>>>
      performGetOwnedAccountsList() => (super.noSuchMethod(
            Invocation.method(
              #performGetOwnedAccountsList,
              [],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Account>>>.value(
                    _FakeEither_0<_i5.Failure, List<_i6.Account>>(
              this,
              Invocation.method(
                #performGetOwnedAccountsList,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Account>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Account>>>
      performGetBelovedAccountsList() => (super.noSuchMethod(
            Invocation.method(
              #performGetBelovedAccountsList,
              [],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Account>>>.value(
                    _FakeEither_0<_i5.Failure, List<_i6.Account>>(
              this,
              Invocation.method(
                #performGetBelovedAccountsList,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Account>>>);
}
