// Mocks generated by Mockito 5.4.1 from annotations
// in griot_app/test/features/accounts/data/repository_impl/accounts_repository_impl_test.dart.
// Do not manually edit this file.

// @dart=2.19

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:griot_app/accounts/data/data_sources/accounts_remote_data_source.dart'
    as _i3;
import 'package:griot_app/accounts/data/models/account_model.dart' as _i2;
import 'package:griot_app/accounts/data/models/beloved_one_model.dart' as _i5;
import 'package:griot_app/core/error/exceptions.dart' as _i7;
import 'package:griot_app/core/network/network_info.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAccountModel_0 extends _i1.SmartFake implements _i2.AccountModel {
  _FakeAccountModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AccountsRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountsRemoteDataSource extends _i1.Mock
    implements _i3.AccountsRemoteDataSource {
  MockAccountsRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.AccountModel> getAccountDetailsFromAPI(
          {required int? accountId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAccountDetailsFromAPI,
          [],
          {#accountId: accountId},
        ),
        returnValue: _i4.Future<_i2.AccountModel>.value(_FakeAccountModel_0(
          this,
          Invocation.method(
            #getAccountDetailsFromAPI,
            [],
            {#accountId: accountId},
          ),
        )),
      ) as _i4.Future<_i2.AccountModel>);
  @override
  _i4.Future<List<_i5.BelovedOneModel>> getBelovedOnesListFromAPI(
          {required int? accountId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBelovedOnesListFromAPI,
          [],
          {#accountId: accountId},
        ),
        returnValue: _i4.Future<List<_i5.BelovedOneModel>>.value(
            <_i5.BelovedOneModel>[]),
      ) as _i4.Future<List<_i5.BelovedOneModel>>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i6.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}

/// A class which mocks [ServerException].
///
/// See the documentation for Mockito's code generation for more information.
class MockServerException extends _i1.Mock implements _i7.ServerException {
  MockServerException() {
    _i1.throwOnMissingStub(this);
  }
}
