// Mocks generated by Mockito 5.4.2 from annotations
// in griot_app/test/features/user/presentation/bloc/users_bloc_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:griot_app/accounts/domain/entities/account.dart' as _i7;
import 'package:griot_app/core/data/main_account_id_provider.dart' as _i8;
import 'package:griot_app/core/error/failures.dart' as _i6;
import 'package:griot_app/user/domain/repository/users_repository.dart' as _i2;
import 'package:griot_app/user/domain/use_cases/get_user_owned_accounts_list_usecase.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUsersRepository_0 extends _i1.SmartFake
    implements _i2.UsersRepository {
  _FakeUsersRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetOwnedAccountsListUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetOwnedAccountsListUseCase extends _i1.Mock
    implements _i4.GetOwnedAccountsListUseCase {
  MockGetOwnedAccountsListUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.UsersRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeUsersRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.UsersRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Account>>> call(
          _i4.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.Account>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.Account>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.Account>>>);
}

/// A class which mocks [MainAccountIdProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockMainAccountIdProvider extends _i1.Mock
    implements _i8.MainAccountIdProvider {
  MockMainAccountIdProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<int> getMainAccountId() => (super.noSuchMethod(
        Invocation.method(
          #getMainAccountId,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);
}
