// Mocks generated by Mockito 5.4.1 from annotations
// in griot_app/test/features/memories/data/repositories/memory_processor_test.dart.
// Do not manually edit this file.

// @dart=2.19

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:griot_app/core/network/network_info.dart' as _i6;
import 'package:griot_app/memories/data/data_source/memories_remote_data_source.dart'
    as _i5;
import 'package:griot_app/memories/data/models/memory_model.dart' as _i2;
import 'package:griot_app/memories/data/models/video_model.dart' as _i3;
import 'package:griot_app/memories/data/repositories/video_processor.dart'
    as _i9;
import 'package:griot_app/memories/domain/entities/memory.dart' as _i4;
import 'package:griot_app/memories/domain/entities/video.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMemoryModel_0 extends _i1.SmartFake implements _i2.MemoryModel {
  _FakeMemoryModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVideoModel_1 extends _i1.SmartFake implements _i3.VideoModel {
  _FakeVideoModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMemory_2 extends _i1.SmartFake implements _i4.Memory {
  _FakeMemory_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMemoriesRemoteDataSource_3 extends _i1.SmartFake
    implements _i5.MemoriesRemoteDataSource {
  _FakeMemoriesRemoteDataSource_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i6.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);
}

/// A class which mocks [MemoriesRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMemoriesRemoteDataSource extends _i1.Mock
    implements _i5.MemoriesRemoteDataSource {
  MockMemoriesRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i2.MemoryModel>> getMemoriesListFromAPI() =>
      (super.noSuchMethod(
        Invocation.method(
          #getMemoriesListFromAPI,
          [],
        ),
        returnValue:
            _i7.Future<List<_i2.MemoryModel>>.value(<_i2.MemoryModel>[]),
      ) as _i7.Future<List<_i2.MemoryModel>>);
  @override
  _i7.Future<_i2.MemoryModel> getMemoryDetailsFromAPI(
          {required int? memoryId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMemoryDetailsFromAPI,
          [],
          {#memoryId: memoryId},
        ),
        returnValue: _i7.Future<_i2.MemoryModel>.value(_FakeMemoryModel_0(
          this,
          Invocation.method(
            #getMemoryDetailsFromAPI,
            [],
            {#memoryId: memoryId},
          ),
        )),
      ) as _i7.Future<_i2.MemoryModel>);
  @override
  _i7.Future<_i2.MemoryModel> postMemoryToAPI({required _i4.Memory? memory}) =>
      (super.noSuchMethod(
        Invocation.method(
          #postMemoryToAPI,
          [],
          {#memory: memory},
        ),
        returnValue: _i7.Future<_i2.MemoryModel>.value(_FakeMemoryModel_0(
          this,
          Invocation.method(
            #postMemoryToAPI,
            [],
            {#memory: memory},
          ),
        )),
      ) as _i7.Future<_i2.MemoryModel>);
  @override
  _i7.Future<_i3.VideoModel> postVideoToAPI({
    required _i8.Video? video,
    required int? memoryId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postVideoToAPI,
          [],
          {
            #video: video,
            #memoryId: memoryId,
          },
        ),
        returnValue: _i7.Future<_i3.VideoModel>.value(_FakeVideoModel_1(
          this,
          Invocation.method(
            #postVideoToAPI,
            [],
            {
              #video: video,
              #memoryId: memoryId,
            },
          ),
        )),
      ) as _i7.Future<_i3.VideoModel>);
  @override
  _i7.Future<int> deleteVideoFromAPI({required int? videoId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteVideoFromAPI,
          [],
          {#videoId: videoId},
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);
  @override
  _i7.Future<_i4.Memory> patchUpdateMemoryToAPI(
          {required _i4.Memory? memory}) =>
      (super.noSuchMethod(
        Invocation.method(
          #patchUpdateMemoryToAPI,
          [],
          {#memory: memory},
        ),
        returnValue: _i7.Future<_i4.Memory>.value(_FakeMemory_2(
          this,
          Invocation.method(
            #patchUpdateMemoryToAPI,
            [],
            {#memory: memory},
          ),
        )),
      ) as _i7.Future<_i4.Memory>);
}

/// A class which mocks [VideoProcessingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockVideoProcessingService extends _i1.Mock
    implements _i9.VideoProcessingService {
  MockVideoProcessingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.MemoriesRemoteDataSource get remoteDataSource => (super.noSuchMethod(
        Invocation.getter(#remoteDataSource),
        returnValue: _FakeMemoriesRemoteDataSource_3(
          this,
          Invocation.getter(#remoteDataSource),
        ),
      ) as _i5.MemoriesRemoteDataSource);
  @override
  _i7.Future<void> deleteVideos({required List<_i8.Video>? videos}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteVideos,
          [],
          {#videos: videos},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
  @override
  _i7.Future<void> addVideos({
    required int? memoryId,
    required List<_i8.Video>? videos,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addVideos,
          [],
          {
            #memoryId: memoryId,
            #videos: videos,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
  @override
  _i7.Future<void> processVideoChanges(
    _i4.Memory? memory,
    _i4.Memory? retrievedMemory,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #processVideoChanges,
          [
            memory,
            retrievedMemory,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}
