// Mocks generated by Mockito 5.4.1 from annotations
// in griot_app/test/features/beloved_ones/data/repository_impl/beloved_ones_repository_impl_test.dart.
// Do not manually edit this file.

// @dart=2.19

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:griot_app/beloved_ones/data/data_sources/beloved_ones_remote_data_source.dart'
    as _i2;
import 'package:griot_app/beloved_ones/domain/entities/beloved_one.dart' as _i4;
import 'package:griot_app/core/network/network_info.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [BelovedOnesRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBelovedOnesRemoteDataSource extends _i1.Mock
    implements _i2.BelovedOnesRemoteDataSource {
  MockBelovedOnesRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.BelovedOne>> getBelovedOnesListFromAPI() =>
      (super.noSuchMethod(
        Invocation.method(
          #getBelovedOnesListFromAPI,
          [],
        ),
        returnValue: _i3.Future<List<_i4.BelovedOne>>.value(<_i4.BelovedOne>[]),
      ) as _i3.Future<List<_i4.BelovedOne>>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i5.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
